# Goal : To say Hello and tell the title / name of repo

# Start with naming the workflow
name: "Hello workflow"

# when the wf runs or triggers
on:
  push:
    

# what the WF does
jobs:

  # Job 1
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello"


  # Job 2
  repo-info:
    runs-on: ubuntu-latest

    steps:
      - name: Show Repository Name
        run: echo "Repository name is ${{ github.repository }}"
